title: 'Block Settings'
fields:
  -
    handle: block_settings
    field:
      type: section
      display: 'Block Settings'
  -
    handle: anchor_id
    field:
      type: text
      display: 'Anchor ID'
  -
    handle: background_colour
    field: common.background_colour
    config:
      default: White
      width: 50
  -
    handle: text_colour
    field: common.colour
    config:
      options:
        -
          key: primary
          value: Primary
        -
          key: secondary
          value: Secondary
        -
          key: tertiary
          value: Tertiary
        -
          key: white
          value: White
        -
          key: gray
          value: Gray
        -
          key: black
          value: Black
        -
          key: default
          value: Default
      default: default
      display: 'Text Colour'
      width: 50
      clearable: true
  -
    handle: padding_top
    field: common.size
    config:
      display: 'Padding Top'
      width: 50
  -
    handle: padding_bottom
    field: common.size
    config:
      display: 'Padding Bottom'
      width: 50
