title: Product
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: image
            field:
              max_files: 1
              min_files: 1
              container: assets
              type: assets
              display: Thumbnail
          -
            handle: supplementary_images
            field:
              container: assets
              type: assets
              display: Images
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
          -
            handle: price
            field:
              type: float
              display: Price
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
